# Docker Compose para backend y base de datos
version: '3.8'
services:

  # Servicio del Backend (NestJS)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001" # El puerto 3001 es el puerto expuesto en la máquina host, 3001 es el que usa la app dentro del contenedor
    environment:
      STAGE: ${STAGE}
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3001
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M           # Límite de memoria para el  backend
          memory_swap: 768M       # Límite de swap a 512 MB para el backend
          cpus: "0.75"             # Límite de CPU a 0.5 núcleos para el backend

  # Servicio de Base de Datos (PostgreSQL)
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M           # Límite de memoria para la base de datos
          memory_swap: 768M      # Límite de swap a 1 GB para la base de datos
          cpus: "0.5"            # Límite de CPU a 0.25 núcleos para la base de datos

networks:
  app-network:
    external: false

volumes:
  db-data:
